# Generated by Django 6.0.1 on 2026-02-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
        ("listings", "0003_remove_listing_category_listing_category_level2_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatthread",
            name="uniq_thread_user_pair",
        ),
        migrations.AddField(
            model_name="chatthread",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_threads",
                to="listings.listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2", "listing"),
                name="uniq_thread_user_pair_listing",
            ),
        ),
    ]
