# Generated by Django 6.0.1 on 2026-01-28 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
            ],
            options={
                'verbose_name': 'Category Level 1',
                'verbose_name_plural': 'Categories Level 1',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2', to='categories.categorylevel1')),
            ],
            options={
                'verbose_name': 'Category Level 2',
                'verbose_name_plural': 'Categories Level 2',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3', to='categories.categorylevel2')),
            ],
            options={
                'verbose_name': 'Category Level 3',
                'verbose_name_plural': 'Categories Level 3',
            },
        ),
        migrations.AddConstraint(
            model_name='categorylevel2',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='uniq_level2_parent_slug'),
        ),
        migrations.AddConstraint(
            model_name='categorylevel3',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='uniq_level3_parent_slug'),
        ),
    ]
