# Generated by Django 6.0.1 on 2026-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorylevel1",
            name="icon_svg",
            field=models.TextField(blank=True, default=""),
        ),
    ]
