# Generated by Django 6.0.1 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_categorylevel1_icon_svg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorylevel1",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name="categorylevel2",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=220),
        ),
        migrations.AlterField(
            model_name="categorylevel3",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=220),
        ),
    ]
