# Generated by Django 6.0.1 on 2026-01-28 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('weight_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('weight_unit', models.CharField(choices=[('ton', 'Ton'), ('kg', 'Kilogram'), ('piece', 'Piece')], max_length=20)),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_unit', models.CharField(choices=[('toman_per_ton', 'Toman per ton'), ('toman_per_kg', 'Toman per kg'), ('toman_per_piece', 'Toman per piece'), ('toman_per_ampere', 'Toman per ampere'), ('negotiable', 'Negotiable')], max_length=30)),
                ('province', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.categorylevel3')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
