# Generated by Django 6.0.1 on 2026-01-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='category_level2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.categorylevel2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='category_level3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.categorylevel3'),
        ),
    ]
